name: Denni CHMI Predpoved

on:
  schedule:
    # Čas je v UTC. 07:15 UTC odpovídá 08:15 našeho času (případně 09:15 letního)
    # Předpověď vychází obvykle kolem 06:50 UTC, takže takto budeme mít jistotu, že už tam je.
    - cron: '15 7 * * *'
  workflow_dispatch: # Přidá na GitHub tlačítko pro ruční spuštění (dobré na testování)

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Stáhnutí kódu
        uses: actions/checkout@v4

      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalace knihoven a prohlížeče
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          playwright install chromium

      - name: Spuštění stahování a odeslání
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py
